#CI configuration goes here..
name: Run UI Test with

on:
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up java17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle build
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: current
          gradle-home-cache-cleanup: true
          add-job-summary-pr-comment: on-failure

      - name: Setup android
        uses: android-actions/setup-android@v3

      - name: Build with gradle
        run: ./gradlew connectedDebugAndroidTest